{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red42\green55\blue62;\red46\green95\blue225;\red245\green245\blue245;
\red204\green0\blue78;\red21\green129\blue62;\red136\green0\blue160;}
{\*\expandedcolortbl;;\cssrgb\c21569\c27843\c30980;\cssrgb\c23137\c47059\c90588;\cssrgb\c96863\c96863\c96863;
\cssrgb\c84706\c10588\c37647;\cssrgb\c5098\c56471\c30980;\cssrgb\c61176\c15294\c69020;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \expnd0\expndtw0\kerning0
\
\pard\pardeftab720\partightenfactor0
\cf3 \cb4 steps:\cb1 \
\pard\pardeftab720\partightenfactor0
\cf5 \cb4 # This step deploys the new version of our container image\cf2 \cb1 \
\cf5 \cb4 # in the cp_ws_1920 Kubernetes Engine cluster.\cf2 \cb1 \
\pard\pardeftab720\partightenfactor0
\cf2 \cb4 - \cf3 name: \cf6 'gcr.io/cloud-builders/kubectl'\cf2 \cb1 \
\cb4 \'a0 \cf3 id: \cf2 Deploy\cb1 \
\cb4 \'a0 \cf3 args:\cb1 \
\cf2 \cb4 \'a0 - \cf6 'apply'\cf2 \cb1 \
\cb4 \'a0 - \cf6 '-f'\cf2 \cb1 \
\cb4 \'a0 - \cf6 'kubernetes.yaml'\cf2 \cb1 \
\cb4 \'a0 \cf3 env:\cb1 \
\cf2 \cb4 \'a0 - \cf6 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'\cf2 \cb1 \
\cb4 \'a0 - \cf6 'CLOUDSDK_CONTAINER_CLUSTER=cp_ws_1920'\cf2 \cb1 \
\
\pard\pardeftab720\partightenfactor0
\cf5 \cb4 # This step copies the applied manifest to the production branch\cf2 \cb1 \
\cf5 \cb4 # The COMMIT_SHA variable is automatically\cf2 \cb1 \
\cf5 \cb4 # replaced by Cloud Build.\cf2 \cb1 \
\pard\pardeftab720\partightenfactor0
\cf2 \cb4 - \cf3 name: \cf6 'gcr.io/cloud-builders/git'\cf2 \cb1 \
\cb4 \'a0 \cf3 id: \cf2 Copy to production branch\cb1 \
\cb4 \'a0 \cf3 entrypoint: \cf2 /bin/sh\cb1 \
\cb4 \'a0 \cf3 args:\cb1 \
\cf2 \cb4 \'a0 - \cf6 '-c'\cf2 \cb1 \
\cb4 \'a0 - |\cb1 \
\cb4 \'a0 \'a0 set -x \cf7 &&\cf2  \\\cb1 \
\cb4 \'a0 \'a0 \cf5 # Configure Git to create commits with Cloud Build's service account\cf2 \cb1 \
\cb4 \'a0 \'a0 git config user.email $(gcloud auth list --filter=status:ACTIVE --format=\cf6 'value(account)'\cf2 ) \cf7 &&\cf2  \\\cb1 \
\cb4 \'a0 \'a0 \cf5 # Switch to the production branch and copy the kubernetes.yaml file from the candidate branch\cf2 \cb1 \
\cb4 \'a0 \'a0 git fetch origin production \cf7 &&\cf2  git checkout production \cf7 &&\cf2  \\\cb1 \
\cb4 \'a0 \'a0 git checkout $COMMIT_SHA kubernetes.yaml \cf7 &&\cf2  \\\cb1 \
\cb4 \'a0 \'a0 \cf5 # Commit the kubernetes.yaml file with a descriptive commit message\cf2 \cb1 \
\cb4 \'a0 \'a0 git commit -m \cf6 "Manifest from commit $COMMIT_SHA\cb1 \
\cb4 \'a0 \'a0 $(git log --format=%B -n 1 $COMMIT_SHA)"\cf2  \cf7 &&\cf2  \\\cb1 \
\cb4 \'a0 \'a0 \cf5 # Push the changes back to Cloud Source Repository\cf2 \cb1 \
\cb4 \'a0 \'a0 git push origin production}